apiVersion: v1
kind: Secret
metadata:
  name: dockify-app-secrets
  namespace: dockify-app
  labels:
    app: dockify-app
type: Opaque
stringData:
  # Database - PostgreSQL via PgBouncer (internal cluster DNS)
  DATABASE_URL: "postgresql://postgres:VuQrkFje2cN7H5cREEbvVyfadVVSMrk1@pgbouncer-service.dockify-app.svc.cluster.local:6432/dockify"

  # Redis (internal cluster DNS)
  REDIS_URL: "redis://redis-service.dockify-app.svc.cluster.local:6379"

  # NextAuth Configuration
  NEXTAUTH_URL: "https://main.dockify.app"
  AUTH_SECRET: "h7394AtzDELVBPuMGJe6vAKOCBRh5a9Fe3lT5Pt8j1c="

  # Email Provider (Resend.com)
  AUTH_RESEND_KEY: "re_jbFpPDdT_AwypjKTP8sCLeavcUcFjVkQv"

  # Environment
  NODE_ENV: "production"
