apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: dockify-app
  labels:
    app: pgbouncer
  annotations:
    io.cilium/lb-ipam-ips: "shared"
    service.cilium.io/global: "true"
spec:
  type: NodePort
  selector:
    app: pgbouncer
  ports:
  - name: pgbouncer
    port: 6432
    targetPort: 6432
    nodePort: 30632
    protocol: TCP
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
