apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: dockify-app
  labels:
    app: nextjs
spec:
  type: ClusterIP
  selector:
    app: nextjs
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  sessionAffinity: ClientIP
